// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("Date('now')");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FiredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Salary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn", "FirstName", "LastName", "Patronymic");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedOn = new DateTime(2020, 5, 11, 17, 18, 41, 240, DateTimeKind.Local).AddTicks(5674),
                            Address = "Винників майдан, 4, Південний Олег, Пакистан",
                            BirthDate = new DateTime(2019, 5, 26, 15, 21, 13, 30, DateTimeKind.Local).AddTicks(2207),
                            Currency = "SRD",
                            Email = "Avrelii31@gmail.com",
                            FiredOn = new DateTime(2020, 9, 25, 7, 26, 30, 790, DateTimeKind.Local).AddTicks(9018),
                            FirstName = "Олесь",
                            LastName = "Горбач",
                            Patronymic = "канд. і. наук",
                            PhoneNumber = "(063) 242-00-09",
                            Position = "Директор",
                            Salary = 8640.73m,
                            Status = "microchip"
                        },
                        new
                        {
                            Id = 2,
                            AcceptedOn = new DateTime(2020, 6, 28, 0, 43, 44, 704, DateTimeKind.Local).AddTicks(5646),
                            Address = "Зелена майдан, 2, Миколаїв, Домініка",
                            BirthDate = new DateTime(2002, 7, 23, 4, 55, 8, 539, DateTimeKind.Local).AddTicks(5814),
                            Currency = "DKK",
                            Email = "Feodosiya_Shudrik@ukr.net",
                            FiredOn = new DateTime(2022, 7, 26, 23, 31, 39, 535, DateTimeKind.Local).AddTicks(6517),
                            FirstName = "Купава",
                            LastName = "Шиян",
                            Patronymic = "проф.",
                            PhoneNumber = "(098) 467-77-24",
                            Position = "Секретар",
                            Salary = 1109.41m,
                            Status = "out-of-the-box"
                        },
                        new
                        {
                            Id = 3,
                            AcceptedOn = new DateTime(2020, 12, 18, 13, 33, 58, 760, DateTimeKind.Local).AddTicks(3459),
                            Address = "Ліста майдан, 633, Східний Тихон, Туніс",
                            BirthDate = new DateTime(2001, 11, 7, 7, 38, 10, 269, DateTimeKind.Local).AddTicks(1720),
                            Currency = "PLN",
                            Email = "Nadiya.Shevchenko39@e-mail.ua",
                            FirstName = "Дарина",
                            LastName = "Кульчицький",
                            Patronymic = "докт. філос. наук",
                            PhoneNumber = "(066) 724-88-61",
                            Position = "Секретар",
                            Salary = 1491.25m,
                            Status = "quantify"
                        },
                        new
                        {
                            Id = 4,
                            AcceptedOn = new DateTime(2021, 7, 29, 13, 41, 12, 576, DateTimeKind.Local).AddTicks(8191),
                            Address = "Зелена майдан, 87, Північний Потап, Ангола",
                            BirthDate = new DateTime(2003, 11, 27, 19, 46, 23, 339, DateTimeKind.Local).AddTicks(333),
                            Currency = "LYD",
                            Email = "Avrelii.Yevpak@gmail.com",
                            FirstName = "Мстислав",
                            LastName = "Луцький",
                            Patronymic = "доц.",
                            PhoneNumber = "(096) 048-05-74",
                            Position = "Прибиральник",
                            Salary = 1687.93m,
                            Status = "deposit"
                        },
                        new
                        {
                            Id = 5,
                            AcceptedOn = new DateTime(2023, 10, 31, 11, 6, 30, 70, DateTimeKind.Local).AddTicks(5180),
                            Address = "пл. Ліста, 408, Західний Віталій, Малайзія",
                            BirthDate = new DateTime(1987, 12, 25, 20, 52, 36, 821, DateTimeKind.Local).AddTicks(8267),
                            Currency = "MOP",
                            Email = "Gorislav_Koman@ukr.net",
                            FiredOn = new DateTime(2019, 12, 14, 8, 39, 2, 524, DateTimeKind.Local).AddTicks(5854),
                            FirstName = "Назар",
                            LastName = "Петлюра",
                            Patronymic = "канд. і. наук",
                            PhoneNumber = "(094) 135-82-41",
                            Position = "Бухгалтер",
                            Salary = 17329.83m,
                            Status = "feed"
                        },
                        new
                        {
                            Id = 6,
                            AcceptedOn = new DateTime(2020, 12, 7, 10, 48, 48, 914, DateTimeKind.Local).AddTicks(449),
                            Address = "Староміська майдан, 276, Західний Лаврентій, Гренада",
                            BirthDate = new DateTime(1991, 10, 1, 17, 11, 6, 530, DateTimeKind.Local).AddTicks(9090),
                            Currency = "NOK",
                            Email = "Timish93@meta.ua",
                            FiredOn = new DateTime(2023, 12, 16, 12, 48, 26, 488, DateTimeKind.Local).AddTicks(1900),
                            FirstName = "Ярополк",
                            LastName = "Ющук",
                            Patronymic = "докт. філос. наук",
                            PhoneNumber = "(044) 484-38-11",
                            Position = "Секретар",
                            Salary = 10031.49m,
                            Status = "bluetooth"
                        },
                        new
                        {
                            Id = 7,
                            AcceptedOn = new DateTime(2022, 2, 19, 15, 22, 22, 353, DateTimeKind.Local).AddTicks(2776),
                            Address = "провулок Вузька, 2, Північний Щастислав, Кіпр",
                            BirthDate = new DateTime(1950, 10, 30, 20, 13, 46, 670, DateTimeKind.Local).AddTicks(4183),
                            Currency = "TZS",
                            Email = "Zoya_Shukhevich29@meta.ua",
                            FiredOn = new DateTime(2022, 10, 16, 13, 7, 11, 299, DateTimeKind.Local).AddTicks(1471),
                            FirstName = "Каріна",
                            LastName = "Гришко",
                            Patronymic = "докт. юрид. наук",
                            PhoneNumber = "(099) 637-95-71",
                            Position = "Прибиральник",
                            Salary = 14488.93m,
                            Status = "Borders"
                        },
                        new
                        {
                            Id = 8,
                            AcceptedOn = new DateTime(2021, 7, 14, 22, 59, 45, 550, DateTimeKind.Local).AddTicks(2129),
                            Address = "Коліївщини майдан, 82, Південний Ярослав, Сенеґал",
                            BirthDate = new DateTime(1981, 4, 9, 2, 33, 9, 625, DateTimeKind.Local).AddTicks(5544),
                            Currency = "XPD",
                            Email = "Stanislava_Storchak36@e-mail.ua",
                            FiredOn = new DateTime(2019, 8, 20, 13, 21, 51, 249, DateTimeKind.Local).AddTicks(7001),
                            FirstName = "Братимир",
                            LastName = "Трясун",
                            Patronymic = "канд. техн. наук",
                            PhoneNumber = "(063) 756-12-21",
                            Position = "Бухгалтер",
                            Salary = 18182.43m,
                            Status = "compressing"
                        },
                        new
                        {
                            Id = 9,
                            AcceptedOn = new DateTime(2022, 5, 18, 22, 54, 7, 734, DateTimeKind.Local).AddTicks(5995),
                            Address = "Староміська майдан, 40, Дніпропетровськ, Тувалу",
                            BirthDate = new DateTime(1959, 10, 2, 1, 14, 33, 635, DateTimeKind.Local).AddTicks(6633),
                            Currency = "ZAR",
                            Email = "Alla_Garai@i.ua",
                            FirstName = "Архип",
                            LastName = "Латан",
                            Patronymic = "доц.",
                            PhoneNumber = "(063) 600-95-43",
                            Position = "Бухгалтер",
                            Salary = 18068.84m,
                            Status = "monetize"
                        },
                        new
                        {
                            Id = 10,
                            AcceptedOn = new DateTime(2022, 10, 24, 1, 59, 19, 240, DateTimeKind.Local).AddTicks(8953),
                            Address = "Нижанківського майдан, 12, Південний Орест, Пакистан",
                            BirthDate = new DateTime(1981, 9, 21, 7, 37, 32, 496, DateTimeKind.Local).AddTicks(603),
                            Currency = "MAD",
                            Email = "Olga71@ex.ua",
                            FiredOn = new DateTime(2022, 3, 8, 11, 55, 5, 264, DateTimeKind.Local).AddTicks(7413),
                            FirstName = "Яровид",
                            LastName = "Дурдинець",
                            Patronymic = "докт. філол. наук",
                            PhoneNumber = "(066) 130-60-67",
                            Position = "Секретар",
                            Salary = 12633.12m,
                            Status = "engineer"
                        },
                        new
                        {
                            Id = 11,
                            AcceptedOn = new DateTime(2023, 1, 25, 11, 28, 5, 353, DateTimeKind.Local).AddTicks(2253),
                            Address = "вулиця Ліста, 406, Західний Максим, Таїланд",
                            BirthDate = new DateTime(1984, 4, 30, 20, 39, 18, 489, DateTimeKind.Local).AddTicks(1141),
                            Currency = "TRY",
                            Email = "Bozhen9@ukr.net",
                            FirstName = "Зоя",
                            LastName = "Коров’як",
                            Patronymic = "проф.",
                            PhoneNumber = "(073) 761-14-85",
                            Position = "Програміст",
                            Salary = 12646.04m,
                            Status = "Bahamian Dollar"
                        },
                        new
                        {
                            Id = 12,
                            AcceptedOn = new DateTime(2024, 1, 28, 12, 33, 44, 651, DateTimeKind.Local).AddTicks(1118),
                            Address = "пров. Нижанківського, 58, Тернопіль, Філіппіни",
                            BirthDate = new DateTime(1958, 2, 3, 10, 30, 19, 274, DateTimeKind.Local).AddTicks(9644),
                            Currency = "THB",
                            Email = "Oleksandra.Ponomariv@e-mail.ua",
                            FiredOn = new DateTime(2021, 1, 1, 23, 1, 38, 546, DateTimeKind.Local).AddTicks(1488),
                            FirstName = "Альвіна",
                            LastName = "Мотрієнко",
                            Patronymic = "докт. пед. наук",
                            PhoneNumber = "(066) 654-30-31",
                            Position = "Директор",
                            Salary = 2035.41m,
                            Status = "Path"
                        },
                        new
                        {
                            Id = 13,
                            AcceptedOn = new DateTime(2021, 8, 7, 17, 30, 42, 572, DateTimeKind.Local).AddTicks(4994),
                            Address = "провулок Молодіжна, 373, Південний Дарій, Сьєрра-Леоне",
                            BirthDate = new DateTime(1976, 9, 12, 21, 46, 17, 232, DateTimeKind.Local).AddTicks(3392),
                            Currency = "ZMK",
                            Email = "Feodosiya_Luckii@ex.ua",
                            FiredOn = new DateTime(2019, 9, 11, 18, 29, 34, 280, DateTimeKind.Local).AddTicks(2334),
                            FirstName = "Аделіна",
                            LastName = "Юхно",
                            Patronymic = "канд. і. наук",
                            PhoneNumber = "(099) 370-74-31",
                            Position = "Програміст",
                            Salary = 5037.51m,
                            Status = "channels"
                        },
                        new
                        {
                            Id = 14,
                            AcceptedOn = new DateTime(2023, 8, 31, 7, 34, 41, 414, DateTimeKind.Local).AddTicks(4020),
                            Address = "пр. Коліївщини, 195, Львів, Боснія і Герцеговина",
                            BirthDate = new DateTime(1965, 11, 4, 20, 16, 57, 307, DateTimeKind.Local).AddTicks(1997),
                            Currency = "IRR",
                            Email = "Diyana98@i.ua",
                            FiredOn = new DateTime(2021, 7, 25, 19, 11, 14, 259, DateTimeKind.Local).AddTicks(4324),
                            FirstName = "Микола",
                            LastName = "Майборода",
                            Patronymic = "канд. психол. наук",
                            PhoneNumber = "(098) 898-00-61",
                            Position = "Секретар",
                            Salary = 3849.04m,
                            Status = "Incredible Metal Mouse"
                        },
                        new
                        {
                            Id = 15,
                            AcceptedOn = new DateTime(2023, 6, 27, 7, 44, 11, 750, DateTimeKind.Local).AddTicks(6354),
                            Address = "Зелена майдан, 051, Єнакієве, Південно-Африканська Республіка",
                            BirthDate = new DateTime(1953, 5, 12, 17, 22, 48, 290, DateTimeKind.Local).AddTicks(4440),
                            Currency = "LSL",
                            Email = "Dobromir_Pavlishin@i.ua",
                            FirstName = "Анфіса",
                            LastName = "Юхно",
                            Patronymic = "канд. психол. наук",
                            PhoneNumber = "(093) 975-58-51",
                            Position = "Директор",
                            Salary = 4671.67m,
                            Status = "Handcrafted Fresh Pants"
                        },
                        new
                        {
                            Id = 16,
                            AcceptedOn = new DateTime(2021, 10, 17, 4, 33, 7, 727, DateTimeKind.Local).AddTicks(3067),
                            Address = "вул. Брюховичів, 5, Ізмаїл, США",
                            BirthDate = new DateTime(2015, 5, 10, 16, 33, 34, 655, DateTimeKind.Local).AddTicks(3503),
                            Currency = "BMD",
                            Email = "Antonida_Petriv21@i.ua",
                            FirstName = "Даромир",
                            LastName = "Балабан",
                            Patronymic = "докт. психол. наук",
                            PhoneNumber = "(050) 571-40-21",
                            Position = "Директор",
                            Salary = 16983.50m,
                            Status = "Tasty Wooden Shoes"
                        },
                        new
                        {
                            Id = 17,
                            AcceptedOn = new DateTime(2021, 7, 11, 11, 37, 12, 808, DateTimeKind.Local).AddTicks(3957),
                            Address = "Брюховичів майдан, 1, Алчевськ, Конго",
                            BirthDate = new DateTime(2018, 4, 12, 3, 49, 44, 782, DateTimeKind.Local).AddTicks(5451),
                            Currency = "XBB",
                            Email = "Anatoliya83@yandex.ua",
                            FiredOn = new DateTime(2021, 11, 30, 7, 40, 21, 406, DateTimeKind.Local).AddTicks(5692),
                            FirstName = "Світлана",
                            LastName = "Петик",
                            Patronymic = "проф.",
                            PhoneNumber = "(097) 454-23-34",
                            Position = "Програміст",
                            Salary = 2067.15m,
                            Status = "Sleek Cotton Towels"
                        },
                        new
                        {
                            Id = 18,
                            AcceptedOn = new DateTime(2022, 9, 5, 21, 43, 14, 237, DateTimeKind.Local).AddTicks(4999),
                            Address = "провулок Молодіжна, 79, Північний Синьоок, Папуа-Нова Гвінея",
                            BirthDate = new DateTime(1976, 12, 16, 1, 19, 12, 217, DateTimeKind.Local).AddTicks(1358),
                            Currency = "TWD",
                            Email = "Yevgen.Yanyuk27@meta.ua",
                            FiredOn = new DateTime(2021, 7, 29, 0, 26, 14, 580, DateTimeKind.Local).AddTicks(1716),
                            FirstName = "Панас",
                            LastName = "Романишина",
                            Patronymic = "канд. юрид. наук",
                            PhoneNumber = "(073) 004-03-16",
                            Position = "Прибиральник",
                            Salary = 10677.41m,
                            Status = "bluetooth"
                        },
                        new
                        {
                            Id = 19,
                            AcceptedOn = new DateTime(2021, 2, 18, 0, 19, 50, 981, DateTimeKind.Local).AddTicks(9381),
                            Address = "пл. Рудного, 8, Біла Церква, Бахрейн",
                            BirthDate = new DateTime(1988, 8, 28, 2, 41, 8, 896, DateTimeKind.Local).AddTicks(8230),
                            Currency = "ANG",
                            Email = "Yaroslav.Gromiko90@ukr.net",
                            FirstName = "Каріна",
                            LastName = "Гладківська",
                            Patronymic = "доц.",
                            PhoneNumber = "(073) 210-12-23",
                            Position = "Прибиральник",
                            Salary = 17852.70m,
                            Status = "productize"
                        },
                        new
                        {
                            Id = 20,
                            AcceptedOn = new DateTime(2023, 5, 5, 12, 16, 22, 671, DateTimeKind.Local).AddTicks(6242),
                            Address = "пров. Коліївщини, 146, Південний Славолюб, Мозамбік",
                            BirthDate = new DateTime(2002, 3, 15, 12, 33, 55, 583, DateTimeKind.Local).AddTicks(8736),
                            Currency = "KES",
                            Email = "Snizhan_Vereshuk62@yandex.ua",
                            FiredOn = new DateTime(2020, 11, 27, 5, 36, 23, 368, DateTimeKind.Local).AddTicks(7776),
                            FirstName = "Соломія",
                            LastName = "Яцишина",
                            Patronymic = "канд. філос. наук",
                            PhoneNumber = "(092) 909-71-48",
                            Position = "Програміст",
                            Salary = 17351.31m,
                            Status = "Configuration"
                        },
                        new
                        {
                            Id = 21,
                            AcceptedOn = new DateTime(2019, 6, 3, 7, 31, 3, 442, DateTimeKind.Local).AddTicks(3742),
                            Address = "проспект Коліївщини, 8, Південний Пантелеймон, Іспанія",
                            BirthDate = new DateTime(2012, 11, 27, 0, 10, 30, 626, DateTimeKind.Local).AddTicks(8091),
                            Currency = "KRW",
                            Email = "Agapiya56@i.ua",
                            FiredOn = new DateTime(2022, 7, 25, 8, 22, 23, 358, DateTimeKind.Local).AddTicks(3115),
                            FirstName = "Зореслава",
                            LastName = "Унич",
                            Patronymic = "докт. пед. наук",
                            PhoneNumber = "(099) 798-84-02",
                            Position = "Директор",
                            Salary = 8573.13m,
                            Status = "synthesizing"
                        },
                        new
                        {
                            Id = 22,
                            AcceptedOn = new DateTime(2022, 4, 11, 0, 14, 25, 780, DateTimeKind.Local).AddTicks(2058),
                            Address = "Зелена майдан, 75, Східний Омелян, Домініканська Республіка",
                            BirthDate = new DateTime(1999, 8, 2, 22, 50, 1, 767, DateTimeKind.Local).AddTicks(3039),
                            Currency = "SBD",
                            Email = "Bozhena_Malkovich73@e-mail.ua",
                            FirstName = "Ганна",
                            LastName = "Лазірко",
                            Patronymic = "канд. філол. наук",
                            PhoneNumber = "(093) 585-94-34",
                            Position = "Прибиральник",
                            Salary = 14655.08m,
                            Status = "Locks"
                        },
                        new
                        {
                            Id = 23,
                            AcceptedOn = new DateTime(2023, 1, 20, 16, 5, 49, 320, DateTimeKind.Local).AddTicks(1449),
                            Address = "Городоцька майдан, 82, Західний Андрій, Конго",
                            BirthDate = new DateTime(1952, 6, 17, 12, 2, 41, 284, DateTimeKind.Local).AddTicks(7040),
                            Currency = "BTN",
                            Email = "Anatolii88@e-mail.ua",
                            FiredOn = new DateTime(2023, 8, 22, 23, 51, 58, 37, DateTimeKind.Local).AddTicks(5853),
                            FirstName = "Валерія",
                            LastName = "Юхно",
                            Patronymic = "докт. політ. наук",
                            PhoneNumber = "(093) 002-40-70",
                            Position = "Прибиральник",
                            Salary = 6781.42m,
                            Status = "Frozen"
                        },
                        new
                        {
                            Id = 24,
                            AcceptedOn = new DateTime(2021, 9, 20, 20, 12, 23, 758, DateTimeKind.Local).AddTicks(2632),
                            Address = "вулиця Вічева, 09, Черкаси, Туреччина",
                            BirthDate = new DateTime(1958, 7, 1, 8, 38, 46, 255, DateTimeKind.Local).AddTicks(2205),
                            Currency = "KHR",
                            Email = "Kii_Gorodocka97@i.ua",
                            FiredOn = new DateTime(2019, 9, 12, 23, 34, 10, 877, DateTimeKind.Local).AddTicks(7558),
                            FirstName = "Яромил",
                            LastName = "Бондаренко",
                            Patronymic = "докт. філос. наук",
                            PhoneNumber = "(096) 596-50-32",
                            Position = "Директор",
                            Salary = 5435.45m,
                            Status = "middleware"
                        },
                        new
                        {
                            Id = 25,
                            AcceptedOn = new DateTime(2021, 1, 8, 8, 47, 30, 423, DateTimeKind.Local).AddTicks(8057),
                            Address = "пр. Стрийська, 7, Південний Омелян, Нова Зеландія",
                            BirthDate = new DateTime(1961, 3, 18, 3, 37, 58, 610, DateTimeKind.Local).AddTicks(9249),
                            Currency = "NZD",
                            Email = "Snizhana31@meta.ua",
                            FiredOn = new DateTime(2020, 6, 15, 19, 28, 3, 572, DateTimeKind.Local).AddTicks(6338),
                            FirstName = "Юхимія",
                            LastName = "Забіла",
                            Patronymic = "канд. політ. наук",
                            PhoneNumber = "(092) 828-12-37",
                            Position = "Прибиральник",
                            Salary = 13739.13m,
                            Status = "Islands"
                        },
                        new
                        {
                            Id = 26,
                            AcceptedOn = new DateTime(2021, 10, 1, 3, 45, 26, 178, DateTimeKind.Local).AddTicks(6068),
                            Address = "Зелена майдан, 0, Черкаси, Латвія",
                            BirthDate = new DateTime(1995, 1, 5, 14, 14, 29, 400, DateTimeKind.Local).AddTicks(2890),
                            Currency = "GBP",
                            Email = "Nazar.Petrin@gmail.com",
                            FiredOn = new DateTime(2022, 11, 30, 3, 18, 39, 896, DateTimeKind.Local).AddTicks(1567),
                            FirstName = "Злата",
                            LastName = "Левадовський",
                            Patronymic = "канд. філос. наук",
                            PhoneNumber = "(050) 497-71-84",
                            Position = "Директор",
                            Salary = 4636.99m,
                            Status = "Wooden"
                        },
                        new
                        {
                            Id = 27,
                            AcceptedOn = new DateTime(2019, 8, 29, 19, 33, 43, 527, DateTimeKind.Local).AddTicks(5321),
                            Address = "вулиця Вічева, 083, Луцьк, Бахрейн",
                            BirthDate = new DateTime(1999, 4, 15, 14, 38, 8, 852, DateTimeKind.Local).AddTicks(4530),
                            Currency = "ISK",
                            Email = "Sologub.Maistrenko@e-mail.ua",
                            FirstName = "Всевлад",
                            LastName = "Осадко",
                            Patronymic = "докт. філол. наук",
                            PhoneNumber = "(092) 611-38-07",
                            Position = "Прибиральник",
                            Salary = 13331.01m,
                            Status = "Credit Card Account"
                        },
                        new
                        {
                            Id = 28,
                            AcceptedOn = new DateTime(2022, 2, 3, 23, 54, 49, 845, DateTimeKind.Local).AddTicks(2194),
                            Address = "Ліста майдан, 8, Рівне, Гватемала",
                            BirthDate = new DateTime(1971, 9, 30, 7, 10, 42, 463, DateTimeKind.Local).AddTicks(9004),
                            Currency = "CZK",
                            Email = "Pavlina18@e-mail.ua",
                            FiredOn = new DateTime(2023, 10, 16, 11, 17, 59, 901, DateTimeKind.Local).AddTicks(5075),
                            FirstName = "Антоніна",
                            LastName = "Петренко",
                            Patronymic = "канд. техн. наук",
                            PhoneNumber = "(044) 954-35-27",
                            Position = "Бухгалтер",
                            Salary = 19323.86m,
                            Status = "Rubber"
                        },
                        new
                        {
                            Id = 29,
                            AcceptedOn = new DateTime(2020, 2, 1, 0, 34, 2, 722, DateTimeKind.Local).AddTicks(2654),
                            Address = "Молодіжна майдан, 9, Північний Олелько, Малаві",
                            BirthDate = new DateTime(2020, 4, 13, 21, 36, 54, 314, DateTimeKind.Local).AddTicks(2180),
                            Currency = "KYD",
                            Email = "Danilo32@e-mail.ua",
                            FirstName = "Святослава",
                            LastName = "Гришко",
                            Patronymic = "проф.",
                            PhoneNumber = "(093) 309-33-49",
                            Position = "Програміст",
                            Salary = 7471.22m,
                            Status = "Officer"
                        },
                        new
                        {
                            Id = 30,
                            AcceptedOn = new DateTime(2022, 8, 4, 3, 24, 58, 776, DateTimeKind.Local).AddTicks(6126),
                            Address = "Нижанківського майдан, 59, Єнакієве, Перу",
                            BirthDate = new DateTime(1972, 5, 17, 7, 45, 53, 546, DateTimeKind.Local).AddTicks(6011),
                            Currency = "GBP",
                            Email = "Kornii.Porivailo49@ex.ua",
                            FirstName = "Яна",
                            LastName = "Латаний",
                            Patronymic = "докт. пед. наук",
                            PhoneNumber = "(073) 196-11-15",
                            Position = "Секретар",
                            Salary = 14989.07m,
                            Status = "Centers"
                        },
                        new
                        {
                            Id = 31,
                            AcceptedOn = new DateTime(2019, 9, 14, 20, 41, 1, 780, DateTimeKind.Local).AddTicks(6210),
                            Address = "Рудного майдан, 857, Одеса, Папуа-Нова Гвінея",
                            BirthDate = new DateTime(1991, 8, 26, 11, 58, 43, 589, DateTimeKind.Local).AddTicks(4108),
                            Currency = "LTL",
                            Email = "Anastas_Demchishina95@gmail.com",
                            FiredOn = new DateTime(2020, 1, 17, 1, 49, 20, 30, DateTimeKind.Local).AddTicks(1930),
                            FirstName = "Мирослава",
                            LastName = "Ялюк",
                            Patronymic = "доц.",
                            PhoneNumber = "(094) 065-82-03",
                            Position = "Бухгалтер",
                            Salary = 4669.78m,
                            Status = "directional"
                        },
                        new
                        {
                            Id = 32,
                            AcceptedOn = new DateTime(2021, 2, 19, 12, 56, 12, 697, DateTimeKind.Local).AddTicks(9521),
                            Address = "пл. Рудного, 7, Вінниця, Гамбія",
                            BirthDate = new DateTime(2020, 5, 12, 16, 39, 36, 591, DateTimeKind.Local).AddTicks(7363),
                            Currency = "ARS",
                            Email = "Krentta.Tarasyuk84@e-mail.ua",
                            FirstName = "Захар",
                            LastName = "Дзюба",
                            Patronymic = "докт. юрид. наук",
                            PhoneNumber = "(044) 314-79-09",
                            Position = "Програміст",
                            Salary = 3752.81m,
                            Status = "Pennsylvania"
                        },
                        new
                        {
                            Id = 33,
                            AcceptedOn = new DateTime(2021, 8, 16, 3, 44, 11, 535, DateTimeKind.Local).AddTicks(2488),
                            Address = "Староміська майдан, 690, Черкаси, Мальдіви",
                            BirthDate = new DateTime(1961, 9, 26, 19, 12, 14, 172, DateTimeKind.Local).AddTicks(1390),
                            Currency = "AWG",
                            Email = "Borimir.Vitrebenko@ukr.net",
                            FiredOn = new DateTime(2019, 11, 10, 6, 17, 12, 985, DateTimeKind.Local).AddTicks(5305),
                            FirstName = "Діяна",
                            LastName = "Юрчишин",
                            Patronymic = "докт. юрид. наук",
                            PhoneNumber = "(063) 021-41-21",
                            Position = "Директор",
                            Salary = 15990.31m,
                            Status = "Human"
                        },
                        new
                        {
                            Id = 34,
                            AcceptedOn = new DateTime(2022, 10, 13, 14, 48, 0, 453, DateTimeKind.Local).AddTicks(3903),
                            Address = "Нижанківського майдан, 1, Північний Борис, Азербайджан",
                            BirthDate = new DateTime(1959, 6, 20, 11, 20, 1, 478, DateTimeKind.Local).AddTicks(7417),
                            Currency = "LVL",
                            Email = "Nadiya.Lugova@i.ua",
                            FirstName = "Ігор",
                            LastName = "Сідлецька",
                            Patronymic = "докт. філос. наук",
                            PhoneNumber = "(092) 324-41-59",
                            Position = "Прибиральник",
                            Salary = 19669.21m,
                            Status = "Idaho"
                        },
                        new
                        {
                            Id = 35,
                            AcceptedOn = new DateTime(2019, 11, 24, 20, 16, 28, 998, DateTimeKind.Local).AddTicks(3874),
                            Address = "Рудного майдан, 93, Східний Олесь, Італія",
                            BirthDate = new DateTime(1971, 8, 4, 5, 10, 13, 658, DateTimeKind.Local).AddTicks(8206),
                            Currency = "BIF",
                            Email = "Vsevolod89@ex.ua",
                            FiredOn = new DateTime(2022, 1, 6, 22, 19, 45, 945, DateTimeKind.Local).AddTicks(8648),
                            FirstName = "Богдана",
                            LastName = "Паламарчук",
                            Patronymic = "канд. техн. наук",
                            PhoneNumber = "(066) 474-54-29",
                            Position = "Прибиральник",
                            Salary = 2893.70m,
                            Status = "COM"
                        },
                        new
                        {
                            Id = 36,
                            AcceptedOn = new DateTime(2022, 1, 31, 10, 59, 49, 791, DateTimeKind.Local).AddTicks(4190),
                            Address = "пл. Ліста, 2, Західний В’ячеслав, Вануату",
                            BirthDate = new DateTime(1977, 4, 19, 7, 38, 30, 83, DateTimeKind.Local).AddTicks(5828),
                            Currency = "BBD",
                            Email = "Shek94@meta.ua",
                            FirstName = "Добромисл",
                            LastName = "Цушко",
                            Patronymic = "доц.",
                            PhoneNumber = "(044) 425-38-39",
                            Position = "Бухгалтер",
                            Salary = 6313.34m,
                            Status = "success"
                        },
                        new
                        {
                            Id = 37,
                            AcceptedOn = new DateTime(2021, 12, 2, 13, 57, 50, 64, DateTimeKind.Local).AddTicks(1372),
                            Address = "Вузька майдан, 06, Чернігів, Вірменія",
                            BirthDate = new DateTime(1984, 7, 3, 12, 45, 1, 26, DateTimeKind.Local).AddTicks(7744),
                            Currency = "JOD",
                            Email = "Zakharii.Yemec@yandex.ua",
                            FiredOn = new DateTime(2019, 11, 3, 12, 7, 39, 803, DateTimeKind.Local).AddTicks(5606),
                            FirstName = "Звенимир",
                            LastName = "Мамій",
                            Patronymic = "канд. психол. наук",
                            PhoneNumber = "(050) 076-86-94",
                            Position = "Секретар",
                            Salary = 6408.64m,
                            Status = "Massachusetts"
                        },
                        new
                        {
                            Id = 38,
                            AcceptedOn = new DateTime(2019, 10, 15, 16, 41, 42, 190, DateTimeKind.Local).AddTicks(6882),
                            Address = "вул. Нижанківського, 4, Львів, Чилі",
                            BirthDate = new DateTime(2016, 5, 18, 8, 42, 41, 439, DateTimeKind.Local).AddTicks(7276),
                            Currency = "GEL",
                            Email = "Maiya_Kalach18@ukr.net",
                            FiredOn = new DateTime(2022, 5, 10, 8, 8, 49, 160, DateTimeKind.Local).AddTicks(2132),
                            FirstName = "Назар",
                            LastName = "Лазірко",
                            Patronymic = "канд. філол. наук",
                            PhoneNumber = "(097) 150-60-28",
                            Position = "Програміст",
                            Salary = 11957.49m,
                            Status = "Persevering"
                        },
                        new
                        {
                            Id = 39,
                            AcceptedOn = new DateTime(2021, 1, 2, 20, 37, 31, 274, DateTimeKind.Local).AddTicks(6103),
                            Address = "Зелена майдан, 7, Бердичів, Чад",
                            BirthDate = new DateTime(1960, 9, 19, 16, 13, 48, 5, DateTimeKind.Local).AddTicks(3037),
                            Currency = "BND",
                            Email = "Bilomir_Gorodockii53@ex.ua",
                            FirstName = "Олексій",
                            LastName = "Уманець",
                            Patronymic = "доц.",
                            PhoneNumber = "(095) 368-32-71",
                            Position = "Секретар",
                            Salary = 12429.48m,
                            Status = "Mobility"
                        },
                        new
                        {
                            Id = 40,
                            AcceptedOn = new DateTime(2024, 3, 7, 7, 35, 12, 271, DateTimeKind.Local).AddTicks(6660),
                            Address = "Городоцька майдан, 338, Західний Анатолій, Нідерланди",
                            BirthDate = new DateTime(1980, 5, 28, 11, 28, 59, 846, DateTimeKind.Local).AddTicks(6370),
                            Currency = "MVR",
                            Email = "Pavlo20@ukr.net",
                            FiredOn = new DateTime(2021, 1, 1, 14, 4, 21, 457, DateTimeKind.Local).AddTicks(3946),
                            FirstName = "Мотря",
                            LastName = "Шупик",
                            Patronymic = "докт. пед. наук",
                            PhoneNumber = "(095) 118-84-45",
                            Position = "Програміст",
                            Salary = 12410.57m,
                            Status = "feed"
                        },
                        new
                        {
                            Id = 41,
                            AcceptedOn = new DateTime(2019, 7, 15, 8, 39, 53, 407, DateTimeKind.Local).AddTicks(4655),
                            Address = "площа Рудного, 3, Північний Ярема, Ангола",
                            BirthDate = new DateTime(1968, 2, 19, 1, 40, 47, 898, DateTimeKind.Local).AddTicks(7352),
                            Currency = "MYR",
                            Email = "Alvina_Umanec60@yandex.ua",
                            FiredOn = new DateTime(2022, 5, 25, 10, 19, 55, 984, DateTimeKind.Local).AddTicks(1194),
                            FirstName = "Костянтин",
                            LastName = "Петренко",
                            Patronymic = "докт. юрид. наук",
                            PhoneNumber = "(073) 826-21-82",
                            Position = "Директор",
                            Salary = 15159.47m,
                            Status = "Tasty Fresh Fish"
                        },
                        new
                        {
                            Id = 42,
                            AcceptedOn = new DateTime(2024, 4, 12, 11, 29, 28, 100, DateTimeKind.Local).AddTicks(1331),
                            Address = "вулиця Брюховичів, 79, Конотоп, Судан",
                            BirthDate = new DateTime(1950, 1, 26, 5, 16, 32, 183, DateTimeKind.Local).AddTicks(1922),
                            Currency = "AMD",
                            Email = "Rodoslav25@ukr.net",
                            FiredOn = new DateTime(2022, 7, 10, 2, 31, 17, 409, DateTimeKind.Local).AddTicks(2863),
                            FirstName = "Віталій",
                            LastName = "Бердник",
                            Patronymic = "канд. юрид. наук",
                            PhoneNumber = "(098) 951-60-64",
                            Position = "Секретар",
                            Salary = 2282.52m,
                            Status = "national"
                        },
                        new
                        {
                            Id = 43,
                            AcceptedOn = new DateTime(2024, 4, 12, 6, 1, 42, 679, DateTimeKind.Local).AddTicks(1014),
                            Address = "Староміська майдан, 4, Лисичанськ, Центральноафриканська Республіка",
                            BirthDate = new DateTime(1966, 8, 31, 22, 3, 27, 206, DateTimeKind.Local).AddTicks(2729),
                            Currency = "BMD",
                            Email = "Mikhailo68@ex.ua",
                            FirstName = "Олександра",
                            LastName = "Громико",
                            Patronymic = "докт. політ. наук",
                            PhoneNumber = "(063) 754-55-34",
                            Position = "Прибиральник",
                            Salary = 4736.30m,
                            Status = "Fords"
                        },
                        new
                        {
                            Id = 44,
                            AcceptedOn = new DateTime(2023, 5, 5, 15, 14, 56, 818, DateTimeKind.Local).AddTicks(4516),
                            Address = "Ліста майдан, 6, Полтава, Болгарія",
                            BirthDate = new DateTime(2004, 11, 9, 22, 17, 32, 475, DateTimeKind.Local).AddTicks(8101),
                            Currency = "CLP",
                            Email = "Mikola35@ex.ua",
                            FirstName = "Валерій",
                            LastName = "Негода",
                            Patronymic = "канд. юрид. наук",
                            PhoneNumber = "(094) 315-47-02",
                            Position = "Бухгалтер",
                            Salary = 1781.86m,
                            Status = "action-items"
                        },
                        new
                        {
                            Id = 45,
                            AcceptedOn = new DateTime(2024, 3, 27, 13, 58, 8, 402, DateTimeKind.Local).AddTicks(8875),
                            Address = "пр. Коліївщини, 02, Львів, США",
                            BirthDate = new DateTime(1996, 9, 22, 23, 35, 13, 959, DateTimeKind.Local).AddTicks(4560),
                            Currency = "AWG",
                            Email = "Smiyana6@yandex.ua",
                            FirstName = "Святослава",
                            LastName = "Миклухо",
                            Patronymic = "докт. техн. наук",
                            PhoneNumber = "(091) 422-88-36",
                            Position = "Бухгалтер",
                            Salary = 13541.92m,
                            Status = "Glen"
                        },
                        new
                        {
                            Id = 46,
                            AcceptedOn = new DateTime(2019, 5, 15, 20, 5, 47, 758, DateTimeKind.Local).AddTicks(1806),
                            Address = "вулиця Винників, 86, Кременчук, Іран",
                            BirthDate = new DateTime(1961, 1, 7, 22, 35, 22, 645, DateTimeKind.Local).AddTicks(7398),
                            Currency = "SBD",
                            Email = "Anna17@gmail.com",
                            FirstName = "Костянтин",
                            LastName = "Боровська",
                            Patronymic = "докт. пед. наук",
                            PhoneNumber = "(094) 040-44-36",
                            Position = "Секретар",
                            Salary = 4761.94m,
                            Status = "Summit"
                        },
                        new
                        {
                            Id = 47,
                            AcceptedOn = new DateTime(2022, 12, 21, 23, 32, 20, 28, DateTimeKind.Local).AddTicks(5357),
                            Address = "Ліста майдан, 120, Івано-Франківськ, Польща",
                            BirthDate = new DateTime(2009, 9, 1, 13, 53, 37, 371, DateTimeKind.Local).AddTicks(8162),
                            Currency = "NIO",
                            Email = "Listvich87@e-mail.ua",
                            FirstName = "Тихон",
                            LastName = "Гнатишин",
                            Patronymic = "докт. техн. наук",
                            PhoneNumber = "(093) 040-11-78",
                            Position = "Бухгалтер",
                            Salary = 15302.68m,
                            Status = "Group"
                        },
                        new
                        {
                            Id = 48,
                            AcceptedOn = new DateTime(2022, 7, 18, 22, 58, 59, 583, DateTimeKind.Local).AddTicks(7661),
                            Address = "вул. Коліївщини, 65, Північний Пилип, Бельгія",
                            BirthDate = new DateTime(1961, 9, 15, 7, 28, 9, 188, DateTimeKind.Local).AddTicks(454),
                            Currency = "CRC",
                            Email = "Zoreslav.Vitrebenko@e-mail.ua",
                            FiredOn = new DateTime(2021, 12, 22, 3, 46, 24, 551, DateTimeKind.Local).AddTicks(8564),
                            FirstName = "Дарій",
                            LastName = "Барановська",
                            Patronymic = "докт. філол. наук",
                            PhoneNumber = "(063) 372-67-02",
                            Position = "Секретар",
                            Salary = 18470.50m,
                            Status = "Specialist"
                        },
                        new
                        {
                            Id = 49,
                            AcceptedOn = new DateTime(2024, 2, 17, 15, 45, 5, 264, DateTimeKind.Local).AddTicks(3297),
                            Address = "площа Вічева, 797, Південний Азарій, Російська Федерація",
                            BirthDate = new DateTime(1973, 2, 13, 2, 42, 53, 736, DateTimeKind.Local).AddTicks(9909),
                            Currency = "CAD",
                            Email = "Danilo_Storchak62@gmail.com",
                            FiredOn = new DateTime(2022, 10, 5, 15, 50, 34, 2, DateTimeKind.Local).AddTicks(1692),
                            FirstName = "Гарнослав",
                            LastName = "Іванців",
                            Patronymic = "докт. техн. наук",
                            PhoneNumber = "(097) 656-47-32",
                            Position = "Бухгалтер",
                            Salary = 18841.70m,
                            Status = "PCI"
                        },
                        new
                        {
                            Id = 50,
                            AcceptedOn = new DateTime(2022, 1, 4, 6, 12, 14, 593, DateTimeKind.Local).AddTicks(5366),
                            Address = "проспект Стрийська, 7, Західний Михайло, Швеція",
                            BirthDate = new DateTime(1984, 6, 1, 7, 22, 50, 183, DateTimeKind.Local).AddTicks(2368),
                            Currency = "MMK",
                            Email = "Aelina_Skoropadska40@ex.ua",
                            FirstName = "Валентин",
                            LastName = "Шупик",
                            Patronymic = "докт. психол. наук",
                            PhoneNumber = "(063) 429-65-10",
                            Position = "Бухгалтер",
                            Salary = 14450.00m,
                            Status = "dedicated"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
